### ISSUE TITLE
'Create Issue' option in the editor's context menu

### ISSUE THREAD

**Issue by Bardin08** [ForNeVeR/Todosaurus#39] opened 2024-04-11 09:29 UTC
It would be wonderful if the option to create an issue in the tracker were available on the editor's context menu. This would allow creating issues without switching to the TODOs window, which can significantly improve user experience. I could create an issue on the fly without disturbing the code-writing process. 

![image](https://github.com/ForNeVeR/Todosaurus/assets/67170413/d11cded7-6f47-4956-b081-01d9657e0db8)

### Additional Context:
- This one could be related to #18.

**Comment by ForNeVeR** [comment] 2024-04-11 09:31
There are plans to make it available from the gutter (#20). Isn't this the same? It will be available in the editor, just like you want.

**Comment by Bardin08** [comment] 2024-04-11 09:33
@ForNeVeR Oh, it's called gutter. My fault, sorry... Should I close this one?

**Comment by ForNeVeR** [comment] 2024-04-11 10:20
Yeah let's close ad duplicate of #20.

**Closed by ForNeVeR** 2024-04-11 10:20 UTC
Labels: enhancement, question
